### ISSUE TITLE
Missing train_mask_8fps/checkpoint-7500

### ISSUE THREAD

**Issue by hoangtnm** [alibaba/animate-anything#1]
Hi, I tried to run inference with instructions from README but I got this error:

```
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like output/latent/train_mask_8fps/checkpoint-7500 is not the path to a directory containing a scheduler_config.json file.
```

It seems that config file`mask_motion_v1/config.yaml` requires `pretrained_model_path: output/latent/train_mask_8fps/checkpoint-7500`, which is not included.

**Comment by daizuozhuo** [comment]
Please change the pretrained model path to your downloaded model path in the config.

**Comment by hoangtnm** [comment]
@daizuozhuo I fixed the issue by replacing it with `output/latent/mask_motion_v1`
