### ISSUE TITLE
Why do you re-prepare the models after saving the states?

### ISSUE THREAD

**Issue by yutaocui** [alibaba/animate-anything#11]
Hi, thanks for your sharing the code. Why do you re-prepare the models after saving the states (https://github.com/alibaba/animate-anything/blob/21f53a07359f7a9a3c8e2a007577111da284a6c2/train_svd.py#L401)? Can I just comment this part?

**Comment by daizuozhuo** [comment]
Yes, this line is unnecessary. You can comment it.
