### ISSUE TITLE
Error when training SVD without mask.

### ISSUE THREAD

**Issue by yunkchen** [alibaba/animate-anything#12]
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[7, 8, 64, 64] to have 9 channels, but got 8 channels instead

**Comment by daizuozhuo** [comment]
Could you provide your training command? You should use the original huggingface svd model for finetuning without mask.

**Comment by xyyandxyy** [comment]
I met the same problem. How did you solve this error?

**Comment by yunkchen** [comment]
> I met the same problem. How did you solve this error?

check your svd model version.

**Comment by Shuweis** [comment]
> > I met the same problem. How did you solve this error?
> 
> check your svd model version.
 
I use the animate_anything_svd_v1.0 which provided in the repo, and also meet the same question, how do you solve it?

**Comment by HaoZhang990127** [comment]
maybe you can use the official svd ckpt [()](https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/tree/main) for training SVD without mask to solve this problem
