### ISSUE TITLE
你好，问个训练问题

### ISSUE THREAD

**Issue by ersanliqiao** [alibaba/animate-anything#2]
这个代码支持加载文生图权重基础上，训练图生视频模型吗

**Comment by zhenghao977** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by daizuozhuo** [comment]
我没这么做过，但是理论上是可以的，需要修改一下load_primary_model函数的代码把文生图的unet权重加载到图生视频的模型里。

**Comment by ersanliqiao** [comment]
那train.py里面main()函数支持图生视频的finetune吗

**Comment by daizuozhuo** [comment]
支持，将config里面的数据集换成自己的数据集就可以了。

**Comment by ersanliqiao** [comment]
<img width="319" alt="image" src="https://github.com/alibaba/animate-anything/assets/8411769/345645e6-55b2-4110-a536-77403c5adb24">
你好，这个json有什么差别吗

**Comment by ersanliqiao** [comment]
多谢解答了，感谢

**Comment by ersanliqiao** [comment]
请问训练要多大显存呢

**Comment by daizuozhuo** [comment]
只训练temporal layer 24G显存可以，全量微调需要30G显存。
