### ISSUE TITLE
How to config lora.yaml

### ISSUE THREAD

**Issue by howardgriffin** [alibaba/animate-anything#25]
When I use the configuration 'lora_training_config.yaml' or 'stable_lora_config.yaml', I got this error `  File "/animate-anything/train.py", line 345, in handle_trainable_modules
    for tm in tuple(trainable_modules):
TypeError: 'NoneType' object is not iterable`

Could you show some correct example  when using config about lora?

**Comment by daizuozhuo** [comment]
currently the code does not support lora training.
