### ISSUE TITLE
Question about the hyper-parameters in finetune_unet function.

### ISSUE THREAD

**Issue by phil329** [alibaba/animate-anything#34]
Thanks for your amazing open-source work!

I have noticed the parameters P_mean=0.7, P_std=1.6 in [train_svd.py](https://github.com/alibaba/animate-anything/blob/HEAD/train_svd.py#L499-L500) 

I have a doubt why do you choose these values and what is the purpose of the noise scheme?

Could you give some more detailed explanation?

**Comment by daizuozhuo** [comment]
I followed the paramters used in SVD paper.
<img width="997" alt="截屏2024-01-23 下午1 49 55" src="https://github.com/alibaba/animate-anything/assets/1107525/52b49fb6-4b94-4268-8a2f-378a2aec7748">
