### ISSUE TITLE
[BUG] 'mask' not found when dataset type is "video_json"

### ISSUE THREAD

**Issue by yunkchen** [alibaba/animate-anything#41]
https://github.com/alibaba/animate-anything/blob/d33431693eb4a76e854c5e6ef65cdea4598db448/utils/dataset.py#L616
example['mask'] ?

**Comment by YujieOuO** [comment]
if self.return_mask:
            mask = get_moved_area_mask(video.permute([0,2,3,1]).numpy())
            example['mask'] = mask

I modified the code like this, and the program runs successfully

**Comment by daizuozhuo** [comment]
Thanks. I have fixed it.
