### ISSUE TITLE
Finetuning animate-anything VRAM issue

### ISSUE THREAD

**Issue by mylee95** [alibaba/animate-anything#44]
I tried to finetune animate-anything model with single sample video preprocessed with Video-BLIP2-Preprocessor Script, using example/train_mask_motion.yaml config file and single A6000 GPU(48GB), but it keeps on getting CUDA out of memory error trying to allocate more than 48GB. 

Then I tried to reduce resolution in config file from 512x512 to 256x256, but it says tensor size does not match while forwarding through unet_3d_blocks.

It would be nice if you can share the config file and GPU that you used to finetune animate-anything with around 30GB VRAM, as it is written in README, and what do we need to do if we are going to downscale the input resolution.

**Comment by efzero** [comment]
You need to change batch size from 8 to around 2 for getting enough VRAM

**Comment by daizuozhuo** [comment]
I update the code for smaller VRAM requirement.
