### ISSUE TITLE
How is LORA used in fine-tuning?

### ISSUE THREAD

**Issue by efzero** [alibaba/animate-anything#45]
Hi there,

First thank you so much for this awesome repo! I had a question about the LORA usage in the fine-tuning stage. Even if I choose "all" parameters to fine tune in the config file, it printed only around 10k parameters are tuned. Are these parameters selected by LORA? Suppose I am tuning on a very different video modality, is it possible that I tune on more parameters? Thanks in advance!

**Comment by daizuozhuo** [comment]
Currently the code does not support LORA training. All parameters are tuning if you choose "all".
