### ISSUE TITLE
typeError: _set_gradient_checkpointing() got an unexpected keyword argument 'value'

### ISSUE THREAD

**Issue by JornyWan** [alibaba/animate-anything#5]
Hi there, I follow your instructions for inference on Colab, after i had downloaded the correct pretrained model and put it under the directory, but received the following error by running the codes:

<img width="884" alt="image" src="https://github.com/alibaba/animate-anything/assets/97571309/eea666c1-5579-4d8d-a058-4a54110764f3">

**Comment by zhenghao977** [comment]
please check the version of the transformers

**Comment by JornyWan** [comment]
> please check the version of the transform

I checked it and the transformers==4.36.2 (it is correct), which is installed with your requirements.txt file.
But it still report this error.

**Comment by throttlekitty** [comment]
I'm having the same issue on windows 11, I also have transformers 4.36.2 installed. On line 146 in train.py, i changed
text_encoder._set_gradient_checkpointing(CLIPEncoder, value=text_enable)
to
text_encoder._set_gradient_checkpointing(CLIPEncoder)
and it runs successfully.

**Comment by daizuozhuo** [comment]
Fixed. Please update code to the latest version.
