### ISSUE TITLE
Running python train.py with example/train_mask_motion.yaml, I get the warning

### ISSUE THREAD

**Issue by xyxxmb** [alibaba/animate-anything#51]
Some weights of UNet3DConditionModel were not initialized from the model checkpoint at output/latent/animate_anything_512_v1.02 and are newly initialized because the shapes did not match:
- conv_in.weight: found shape torch.Size([320, 4, 3, 3]) in the checkpoint and torch.Size([320, 5, 3, 3]) in the model instantiated

I want to know whether has some problems?

**Comment by daizuozhuo** [comment]
Yes, there is something wrong with your training command. Could you paste your running command here?

**Comment by daizuozhuo** [comment]
Please ignore this warning.
