### ISSUE TITLE
train_svd.py error

### ISSUE THREAD

**Issue by shaowujie** [alibaba/animate-anything#54]
你好，我在进行微调的时候遇到如下问题，请问一下如何解决呢？
运行命令如下：
accelerate launch --config_file example/deepspeed.yaml train_svd.py --config example/train_svd_mask.yaml pretrained_model_path=output/latent/animate_anything_512_v1.02

其中pretrained_model_path模型来自read.me
进行fine-tune时候报错：
  File "/animate-anything/train_svd.py", line 89, in load_primary_models
    pipeline = StableVideoDiffusionPipeline.from_pretrained(pretrained_model_path)
  File "/home/admin/anaconda3/envs/animation/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1352, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_video_diffusion.pipeline_stable_video_diffusion.StableVideoDiffusionPipeline'> expected {'scheduler', 'unet', 'image_encoder', 'vae', 'feature_extractor'}, but only {'unet', 'scheduler', 'vae'} were passed.

非常希望能收到您的答复。

**Comment by shaowujie** [comment]
使用：stabilityai/stable-video-diffusion-img2vid

**Comment by sculmh** [comment]
你应该下载错模型了，svd微调的模型名带有svd后缀，animate_anything_svd_v1.0.tar
