### ISSUE TITLE
error: "AttributeError: 'DistributedDataParallel' object has no attribute 'enable_gradient_checkpointing'"

### ISSUE THREAD

**Issue by shaowujie** [alibaba/animate-anything#55]
thanks for your great work!

I encountered an error while executing the command, that "python train_svd.py --config example/train_svd.yaml pretrained_model_path=stabilityai/stable-video-diffusion-img2vid/".

error detail:
Traceback (most recent call last):
  File "/checkpoint/binary/train_package/./train_svd.py", line 840, in <module>
    main(**args_dict)
  File "/checkpoint/binary/train_package/./train_svd.py", line 599, in main
    unet_and_text_g_c(
  File "/checkpoint/binary/train_package/./train_svd.py", line 107, in unet_and_text_g_c
    unet.enable_gradient_checkpointing()
  File "/root/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'enable_gradient_checkpointing'

I want to know how to solve this problem. This problem has been bothering me for a long time.

**Comment by shaowujie** [comment]
I have only one A800 GPU

**Comment by sculmh** [comment]
It seems you are using DistributedDataParallel (DDP) to wrap unet. You could try calling unet_and_text_g_c() before DDP.

**Comment by sculmh** [comment]
try unet.module. enable_gradient_checkpointing()

**Comment by shaowujie** [comment]
modify unet.enable_gradient_checkpointing() ->  unet.module.enable_gradient_checkpointing().
commit
