### ISSUE TITLE
请问 /webvid/webvid/data/40K.json 数据格式是什么样的？

### ISSUE THREAD

**Issue by cklogic** [alibaba/animate-anything#57]
有样例吗？谢谢啦~

**Comment by sculmh** [comment]
Please refer to  VideoJsonDataset .__item__ (util/dataset.py), Videojson contains list of dict like {'caption': 'xxx', 'video': 'path'}.

**Comment by sculmh** [comment]
Please refer to VideoJsonDataset .item (util/dataset.py), Videojson contains list of dict like {"caption": "xxx", "video": "path"}.                [{"caption": "Motion around stack of large mesh bags in food warehouse ', 'video': '000051_000100/1066665592.mp4"}]

**Comment by sculmh** [comment]
Please refer to VideoJsonDataset.__get_item__ (util/dataset.py), Videojson contains list of dict like {"caption": "xxx", "video": "path"}. [{"caption": "Motion around stack of large mesh bags in food warehouse ', 'video': '000051_000100/1066665592.mp4"}]
